name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build project
        run: |
          mkdir public
           cp -r $(find . -type f ! -path "./public/*") public/
          echo "Build complete"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: public

  deploy_pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact-name: github-pages
